### ISSUE TITLE
Suggestion: World View of a Minecraft map using https://globekit.co/

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#104]
I was reading about a controversy of Github stealing Stripes 3D globe and in the process found the framework used to make a big 3D globe.
Though it would be epic to somehow show the Minecraft world (atlas map) on this! https://globekit.co/

Stripe: how its made https://stripe.com/blog/globe
Github how its made https://github.blog/2020-12-21-how-we-built-the-github-globe/

**Comment by Happyrobot33** [comment]
one big problem I see with implementing this is infinite worlds with indefinite dimensions

**Comment by JLyne** [comment]
I'm going to say no to this for now as it's out of scope for what I would like LiveAtlas to be
