### ISSUE TITLE
More of help

### ISSUE THREAD

**Issue by squeaky2137** [JLyne/LiveAtlas#12]
Couldn’t find way to contact so I need le help.
1. How do I clear cdn caches
2. How to make le file read only.
3. There is no three is just isn’t workin so guessin cause need to clear cdn caches

**Comment by JLyne** [comment]
> How do I clear CDN caches
This is only something you need to worry about if you actually have a CDN, such as Cloudflare or KeyCDN. If you aren't sure whether you have one, you probably don't.

> How to make le file read only.
Best you look up how to do this for particular OS. [Here is a guide for windows](https://www.wikihow.com/Make-a-File-Read-Only)
