### ISSUE TITLE
Can't see player markers, Pl3xMap

### ISSUE THREAD

**Issue by srnyx** [JLyne/LiveAtlas#125]

**Comment by JLyne** [comment]
I'm unable to reproduce this on a local Pl3xmap installation 
![image](https://user-images.githubusercontent.com/4615316/133428387-17d53383-55e8-445b-b454-2eefd8922448.png)

If you're still encountering this issue, please reopen and provide your Pl3xmap config.yml and LiveAtlas version

**Comment by srnyx** [comment]
> Pl3xmap config.yml

https://paste.srnyx.xyz/jizodoqomu.yaml


> LiveAtlas version

2.0.0-beta.3

**Comment by srnyx** [comment]
@JLyne No clue if you get notified for closed issues so just gonna mention you to be sure you see this.

**Comment by JLyne** [comment]
Sorry for the delay, managed to reproduce this so will reopen
