### ISSUE TITLE
[Pl3xMap] Support heads-url setting

### ISSUE THREAD

**Issue by galacticwarrior9** [JLyne/LiveAtlas#134]
If `heads-url` is set in Pl3xMap's config.yml - assuming the `nameplate` section is enabled - skins will default to Steve on the map. This has been tested using Pl3xMap build 162 and [this build](https://github.com/JLyne/LiveAtlas/actions/runs/1231413913) of LiveAtlas.

**Comment by JLyne** [comment]
The `heads-url` setting is supported as of 3.0.0-beta.2
