### ISSUE TITLE
Player marker is higher than map marker

### ISSUE THREAD

**Issue by WattGuy** [JLyne/LiveAtlas#14]
The regular marker is located lower in the layer than the player marker. Is it possible to fix this?
![example](https://user-images.githubusercontent.com/47968848/107545609-af787a00-6bf5-11eb-9a61-842256ec0e02.png)

**Comment by JLyne** [comment]
A `playersAboveMarkers` config option has been added to index.html's `liveAtlasConfig`. It defaults to true to match old behaviour, but can be set to false which will display player markers below other marker types.
