### ISSUE TITLE
Documentation misleading

### ISSUE THREAD

**Issue by gbl** [JLyne/LiveAtlas#148]
The documentation for pl3xmap has a `Download the latest release` link, which leads to version 1.3.2, which doesn't work with pl3xmap.

The `Configuring-Multiple-Servers` page has an example with a pl3xmap config, where the pl3xmap field does not end in a `/`. Omitting this trailing slash caused multiple problems for me, like links not working and trying to load the .js scripts from the wrong directory; I suggest adding it to the config, and to the list of individual URLs in item 4 ("Test").

**Comment by JLyne** [comment]
The latest available version is now 2.0.0 which resolves the first point.
The second part was fixed in 0ae8b11 and the documentation has been updated
