### ISSUE TITLE
render artifact

### ISSUE THREAD

**Issue by XuPuPG** [JLyne/LiveAtlas#15]
Yandex browser 88.0.4324.1097 
![image](https://user-images.githubusercontent.com/11676369/108506763-647ff600-72ca-11eb-981b-d2ff39f8bc8d.png)
![image](https://user-images.githubusercontent.com/11676369/108506831-7c577a00-72ca-11eb-8243-fabbe6c0e091.png)

**Comment by JLyne** [comment]
I'm not able to reproduce this myself on Yandex. Are you aware of a way to reproduce this reliably?
Might also be worth checking this isn't a device specific issue, as the artifacts there would suggest possible GPU issues to me.

![image](https://user-images.githubusercontent.com/4615316/108793563-b56a4580-757b-11eb-9b44-d9acf703b127.png)

Will close for now, but happy to look at this again if more information surfaces.
