### ISSUE TITLE
Can't disable chat button

### ISSUE THREAD

**Issue by LiskoSlayer63** [JLyne/LiveAtlas#16]
`allowwebchat` is set to `false` and `org.dynmap.SimpleWebChatComponent` is fully disabled, but the chat button is still visible on website. Using external web server (IIS).

**Dynmap version:** 3.1 for Forge 1.16.5

**Comment by JLyne** [comment]
LiveAtlas is currently mirroring dynmap behaviour here, which is to show the chatbox regardless of the value of `allowwebchat`, as long as the `chatbox` client component is enabled. You'll have to comment that one out too to hide the button.

I'm up for changing this if the chatbox is indeed useless without `allowwebchat`, and there isn't a dynmap api that allows it to be used for non-chat messages. I haven't looked into this enough to be confident right now though.
