### ISSUE TITLE
Title won't change

### ISSUE THREAD

**Issue by PokeyLuxury** [JLyne/LiveAtlas#17]
The title won't change i editted <title> Dynamic Map </title> But it says A simple survival server.

**Comment by thecharlie654** [comment]
I have a similar problem, but mine is stuck at 0.0.0.0

**Comment by JLyne** [comment]
The title in `<title>` is only used as a fallback until the server configuration is retrieved, after which it is replaced with the defined `webpage-title` in dynmap's config.
