### ISSUE TITLE
Map types showing 'dimension' for different dimensions instead of the dimensions' names

### ISSUE THREAD

**Issue by thecharlie654** [JLyne/LiveAtlas#18]
![image](https://user-images.githubusercontent.com/49923828/108829619-4cf18780-75c0-11eb-95c3-3292dab072c7.png)

As shown above, for me, the dimensions are only being named as 'dimension'.
Is there a config file where I can fix this?

**Comment by JLyne** [comment]
Sorry for the late reply.

If this is still an issue you are encountering, do you have a link to your map I could use to investigate?

**Comment by JLyne** [comment]
Will close this for now. Feel free to reopen if you're still having this problem.
