### ISSUE TITLE
Skins do not appear

### ISSUE THREAD

**Issue by galacticwarrior9** [JLyne/LiveAtlas#2]
Hi there,

Skins do not appear on the web interface when a server is in offline mode and LiveAtlas is installed. You can observe this on our [map](https://map.ccnetmc.com/townymap/). 

The issue persists even if the following settings are enabled: 

```
# Control loading of player faces (if set to false, skins are never fetched)
fetchskins: true

# Control updating of player faces, once loaded (if faces are being managed by other apps or manually)
refreshskins: true

# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "https://cravatar.eu/avatar/%player%/16.png"
```

Dynmap's SkinsRestorer integration also fails to rectify the issue when enabled (`skinsrestorer-integration: true`). 

This occurs on both Dynmap v3.1-beta5 and Dynmap v3.1-beta4. Skins can be seen normally on the default web interface.

**Comment by JLyne** [comment]
Whoops, I was using the `name` property of players when getting skin images, instead of `account`. Looks like on your server player names have HTML in them, which broke everything.
Just pushed a fix, will release a 0.4.1 including it later today.

**Comment by galacticwarrior9** [comment]
Thank you, the latest update has restored skins to the map! 

However, it does not appear to have worked for the player widget, where the heads have the Steve skin ([example](https://map.ccnetmc.com/townymap/#world;flat;-9168,64,10352;0)) - is this a related issue?

**Comment by JLyne** [comment]
Ah a bit of an oversight on my part, all the player heads in the lost are currently hardcoded to Steve. I'll get that sorted.

**Comment by galexrt** [comment]
@JLyne Not sure if this is related as the server I'm experiencing this with is in online mode.

The player skins / icons are shown correctly **on the map** but no the players list it seems:
![image](https://user-images.githubusercontent.com/3718398/102952311-26837300-44cf-11eb-8169-ff1afe208b3a.png)

The skin is loaded correctly but the name and player list are not showing the right skin and name.

This is with the v0.4.1.

**Comment by JLyne** [comment]
The skin issue is straightforward as showing skins in the player list simply wasn't implemented at all. I've got a fix for this locally currently.

The name issue is odd though as Steve is a fallback name that's only shown if dynmap doesn't return a name for a player (which to my understanding shouldn't ever happen).

Do you have a link to the map showing this issue? Failing that, a copy of your dynmap_config.json and dynmap_<world>.json files could work instead.

**Comment by galexrt** [comment]
I'm going to post the files tomorrow morning, as it is quiet late here.

Do you want the files from when players are on the server, no one is on the server or both scenarios?

**Comment by JLyne** [comment]
Whenever you're able to that's fine. With players would be best if possible.

**Comment by JLyne** [comment]
Looking into the dynmap configuration.txt a little more, I've noticed there is a `hidenames` option. Enabling that results in the behaviour you described above, so perhaps you have that setting enabled?

In either case LiveAtlas isn't handling it correctly, as it is showing Steve rather than no name at all, so I'll get that fixed.

**Comment by JLyne** [comment]
I believe this to be fixed with v0.4.2. Feel free to reopen if you're still having problems.

**Comment by HerrMelodious** [comment]
Hi there,

I have this problem with a fresh isntalled copy of LiveAtlas 2.0.0 Beta 1 (because of 1.17+ support).
Internal Dynmap Webserver. 

![grafik](https://user-images.githubusercontent.com/88331632/127885821-e10c8462-5705-4312-94dd-5b0c96598e20.png)

Standard dynmap frontend shows skins correctly.

http://minecraftserver.bz:8080

**Comment by JLyne** [comment]
Should be fixed in the latest commit. You can wait for the next release or try [this version](https://github.com/JLyne/LiveAtlas/actions/runs/1090922668) in the meantime
