### ISSUE TITLE
Is there a way to customize the Icons for Templates?

### ISSUE THREAD

**Issue by Compithegreat** [JLyne/LiveAtlas#20]
I haven't found any file containing the HD template icon, nor any reference to it, so I'm assuming no.

**Comment by JLyne** [comment]
Sorry for the late reply.

Unfortunately the only way to change the icons at present is to build your own copy of LiveAtlas with your desired replacements included. Each icon is a separate svg file in `src/assets/icons`

**Comment by Compithegreat** [comment]
> Sorry for the late reply.
> 
> Unfortunately the only way to change the icons at present is to build your own copy of LiveAtlas with your desired replacements included. Each icon is a separate svg file in `src/assets/icons`

I thought so. Thanks!
