### ISSUE TITLE
Back Background.... How to make it transparent?

### ISSUE THREAD

**Issue by CloudeLecaw** [JLyne/LiveAtlas#201]
![image](https://user-images.githubusercontent.com/12080017/137257772-0df8d15d-2807-4897-9f2d-d0caf629e7c1.png)

Any Chance to change the black to a transparent Background?

Or to Switch back to the smaller Background of the old Version without the dot markers..( there playerheads or miniatures of players where instead of markers)

Or any chance to bring back the beta3 view to beta4
![image](https://user-images.githubusercontent.com/12080017/137258183-d8a9ead3-6061-4027-b49c-0fe660bfcdc1.png)
Even here it would be nice to be able to change the Background color to transparent or nearly transparent...

**Comment by JLyne** [comment]
Next release will include a `compactPlayerMarkers` index.html option, which will use a marker style similar to <=beta3.

Also added `--background-marker` and `--text-marker` CSS variables to allow customising the colours. In your case you can enable `compactPlayerMarkers` and set an appropriate `rgba()` value for `--background-marker` to make the background semi-transparent.
