### ISSUE TITLE
Ability to disable playerlist

### ISSUE THREAD

**Issue by galexrt** [JLyne/LiveAtlas#21]
Is there a way to disable the playerlist in LiveAtlas or is there a way to do that with dynmap that I haven't found yet?

I have checkd the dynmap wiki and issues, but I have only found ways that modify the javascript of the dynmap's javascript code directly.

**Comment by WayneBuckhanan** [comment]
Not a full fix, but you should be able to comment out the `playermarkers` section in the dynmap/configuration.txt file and dynmap won't show that layer's information. Dymap and LiveAtlas both still show the player icon/heading, but shows 0 players.

```
#  - class: org.dynmap.ClientComponent
#    type: playermarkers
#    ...
```

**Comment by JLyne** [comment]
LiveAtlas will now hide the player list when `playermarkers` is turned off.
