### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by Woutdvv** [JLyne/LiveAtlas#211]
On the orginal dynmap, people are sorted by their suffix in the tab. If you have [group1] name, [group1] name2 than all the group 1’s are under eachother and after that all people with group 2 etc etc

in this overlay, all the names are mixed..

how to fix?

**Comment by JLyne** [comment]
Sorry for the delay in looking at this.
Do you have a link to a map that has this issue (with or without LiveAtlas is fine)? There's likely a specific configuration that LiveAtlas doesn't support correctly here.

**Comment by JLyne** [comment]
Closing this for now as not had a reply. Feel free to reopen if you're still encountering the issue and have more information.
