### ISSUE TITLE
Default dynmap after refresh

### ISSUE THREAD

**Issue by Suntrux** [JLyne/LiveAtlas#22]
Hello, i am having a problem that when i reload my dynmap the default dynmap look returns,
when you click the link icon on the down left side it show the LiveAtlas interface, but it won't stay like that
http://play.multumcraft.nl:8122/#IridiumSkyblock;flat;252,64,12;0
I have the exact same web folder as my survival server but it still doesn't work :/
 
[web.zip](https://github.com/JLyne/LiveAtlas/files/6447163/web.zip)
This is my web folder, thank you for this great dynmap interface

**Comment by lukaslangrock** [comment]
Have you tested it in a private tab? The default dynmap website might be cached and thus loaded from cache when you refresh the site, I have the exact same problem with my own dynmap on my phone.

**Comment by Suntrux** [comment]
> Have you tested it in a private tab? The default dynmap website might be cached and thus loaded from cache when you refresh the site, I have the exact same problem with my own dynmap on my phone.

Hey, thanks for letting me know this, this was indeed the problem!
Thanks youuuuu
