### ISSUE TITLE
Doesn't work with Pl3xmap.

### ISSUE THREAD

**Issue by kerostampcrab** [JLyne/LiveAtlas#232]
index.html: https://paste.sparked.host/xisokuzole.xml

I followed the instructions for the Pl3xmap installation on the wiki, however after installation it doesn't seem to work: 
![image](https://user-images.githubusercontent.com/68773973/139580174-88f08c52-2142-4e7d-ab00-7127b9effec9.png)
I tried for Dynmap and it works without any problems.
Version: live-atlas-2.0.0-beta.4
IP for Pl3xmap/LiveAtlas: map.floofhub.cf:25846

**Comment by JLyne** [comment]
You appear to have a syntax error in your configuration:

    servers: {
        // Pl3xmap internal webserver configuration
         pl3xmap: {
              pl3xmap: window.location.pathname
         },
         //...
should be:

    servers: {
        // Pl3xmap internal webserver configuration
         pl3xmap: {
              pl3xmap: window.location.pathname
         },
    },
    //...

Everything else seems fine from what I can see, but if you continue to have problems there is likely additional information in your browser console.

**Comment by kerostampcrab** [comment]
I actually had tried that exact same syntax  that you told me to replace it with before, but it doesn't work. https://paste.sparked.host/aqiqevofur.js

It does have console errors, I just don't understand them.
This is the line my console told me there are errors or something 
https://paste.sparked.host/gigonuteja.csharp

**Comment by JLyne** [comment]
You appear to have uncommented a comment on line 6 of the config in the first link, that'd be causing a JS error preventing the config from being loaded correctly,

**Comment by kerostampcrab** [comment]
Oh wow, completely my bad. I knew that wasn't supposed to be uncommented, I guess i accidentally did because I kept reversing LiveAtlas so I would always uncomment those things.
