### ISSUE TITLE
DiscordSRV messages not present in web chat

### ISSUE THREAD

**Issue by iialexidai** [JLyne/LiveAtlas#242]
Messages from Discord via DiscordSRV do not appear in the webchat interface when using LiveAtlas while they do with the default Dynmap interface.

**Comment by JLyne** [comment]
Do you have a link to a map that demonstrates the issue? I currently don't have an easy way to test DiscordSRV so that would be appreciated.

**Comment by iialexidai** [comment]
Yes https://dynmap.dogsalot.nexbyte.cloud:2054
I had to reenable the webchat in the config

Also here's a picture of what should happen using the normal dynmap UI
1st message is sent from the webchat
2nd message from Discord via DiscordSRV
3rd message from the Minecraft server's chat
![dynmapDefaultUI](https://user-images.githubusercontent.com/65917239/141382237-a6afe7df-2fc8-493c-a0ba-9b7b57c6a971.png)
Here's what happens with LiveAtlas
![dynmapLiveAtlasUI](https://user-images.githubusercontent.com/65917239/141382322-e348511b-6190-4d2e-9657-42151389ddc4.png)

**Comment by JLyne** [comment]
Will be fixed in the next release. LiveAtlas was ignoring messages that didn't have a `web` or `player` source, and messages sent via the dynmap API have a `plugin` source.

**Comment by iialexidai** [comment]
Alright thanks 👍🏻
