### ISSUE TITLE
Map icon not updating

### ISSUE THREAD

**Issue by DerLukas01** [JLyne/LiveAtlas#25]
I have a custom nehter generated named like "world_nether_custom" and all I get is the standard "flat" overworld icon instead of the "nether flat" and "nether surface"

Haven't found a way to change the svg data.

**Comment by JLyne** [comment]
I've tweaked the world name checks so the correct icon is displayed in more cases. Sadly dynmap doesn't provide the world type so guessing based on the name is the only option.

The fix will be included in the next release which will hopefully be today.

**Comment by RuofengX** [comment]
So how to change the world icon? Changing the name of icon file in images folder to the 'world + map'?
