### ISSUE TITLE
[Dynmap] Implement sidebarmarkers component

### ISSUE THREAD

**Issue by LightningXCE** [JLyne/LiveAtlas#266]
Hi there,

With Dynmap, enabling the `sidebarmarkers` component by adding 
```
  - class: org.dynmap.ClientComponent
    type: sidebarmarkers
    title: 'Markers (current world)'
```
to the configuration allows users to see a list of all markers on the current world (see https://gfycat.com/entireapprehensiveichthyosaurs).

With LiveAtlas, there doesn't seem to be any visible way to view the list when enabled. I would expect another button in the top-right or a continuation of the map button to have the list visible. Am I possibly just missing something on my end?

Thanks!

**Comment by JLyne** [comment]
`sidebarmarkers` currently isn;t supported by LiveAtlas. If I'm honest I didn't know it existed until recently when I found a random reddit post talking about it, as it's not in the config by default anymore.

I'd like to support it at some point though so it's one for the list.

**Comment by LightningXCE** [comment]
Ah awesome, thanks! Great to know!

**Comment by JLyne** [comment]
3.0.0-beta.1 now includes a markers list in the sidebar which mirrors much of the functionality of `sidebarmarkers`.
