### ISSUE TITLE
No configuration found

### ISSUE THREAD

**Issue by redxon** [JLyne/LiveAtlas#288]
Hello

I have set up LiveAtlas multiserver but I can not get it to work. I have done everything as it should be in the wiki.

Here is my error:
`LiveAtlas configuration is invalid:
No configuration found.
Check for any syntax errors in your configuration in index.html. Your browser console may contain additional information.`

And console 
`Uncaught SyntaxError: Unexpected identifier
index.432fd330.js:36 LiveAtlas version 2.0.0 - https://github.com/JLyne/LiveAtlas
index.432fd330.js:36 LiveAtlas configuration is invalid:  No configuration found.
Check for any syntax errors in your configuration in index.html. Your browser console may contain additional information.
    at Sn (https://minecraft.domain.ch/live-atlas/assets/index.432fd330.js:34:594)
    at https://minecraft.domain.ch/live-atlas/assets/index.432fd330.js:36:717
(anonymous) @ index.432fd330.js:36
DevTools failed to load source map: Could not load content for chrome-extension://gabdloknkpdefdpkkibplcfnkngbidim/maps/content.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

and my config:

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="preload" href="https://fonts.gstatic.com/s/raleway/v22/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCIPrE.woff2" as="font" crossorigin="anonymous">
    <link rel="preload" href="https://fonts.gstatic.com/s/raleway/v22/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVsEpbCIPrE.woff2" as="font" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">

	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

    <meta name="theme-color" content="#222222">
	<link rel="manifest" href="./live-atlas/favicons/site.webmanifest">
	<link rel="icon" href="./live-atlas/favicons/favicon.svg">
    <link rel=”mask-icon” href="./live-atlas/favicons/mask.svg" color="#cccccc">
    <link rel="apple-touch-icon" sizes="180x180" href="./live-atlas/favicons/apple-touch-icon.png">

    <meta name="keywords" content="minecraft, map, dynamic, liveatlas" />
	<meta name="description" content="Minecraft Dynamic Map" />

    <title>Minecraft Dynamic Map - LiveAtlas</title>

    <script>
        window.liveAtlasConfig = {
        	// By default LiveAtlas looks for a dynmap standalone/config.js file
            // This configuration can be used instead to support Pl3xmap installations multiple servers
            // To configure multiple servers, see https://github.com/JLyne/LiveAtlas/wiki/Configuring-Multiple-Servers.
            // servers: {
                // Pl3xmap internal webserver configuration
                // pl3xmap: {
            	// 	pl3xmap: window.location.pathname
                // },

                // Dynmap internal webserver configuration without using standalone/config.js
                // dynmap: {
            	//   dynmap: {
                //     configuration: 'standalone/dynmap_config.json?_={timestamp}',
                //     update: 'standalone/dynmap_{world}.json?_={timestamp}',
                //     sendmessage: 'standalone/sendmessage.php',
                //     login: 'standalone/login.php',
                //     register: 'standalone/register.php',
                //     tiles: 'tiles/',
                //     markers: 'tiles/'
                //   }
                // },

                 Multiple Dynmap servers on external webserver configuration
                 old: {
                     label: 'Old-World',
                     dynmap: {
                         configuration: 'https://minecraft.domain.ch/old/standalone/MySQL_configuration.php',
                         update: 'https://minecraft.domain.ch/old/standalone/MySQL_update.php?world={world}&ts={timestamp}',
                         sendmessage: 'https://minecraft.domain.ch/old/standalone/MySQL_sendmessage.php',
                         login: 'https://minecraft.domain.ch/old/standalone/MySQL_login.php',
                         register: 'https://minecraft.domain.ch/old/standalone/MySQL_register.php',
                         tiles: 'https://minecraft.domain.ch/old/standalone/MySQL_tiles.php?tile=',
                         markers: 'https://minecraft.domain.ch/old/standalone/MySQL_markers.php?marker='
                     }
                 },
                 new: {
                     label: 'New-World',
                     dynmap: {
                         configuration: 'https://minecraft.domain.ch/new/standalone/MySQL_configuration.php',
                         update: 'https://minecraft.domain.ch/new/standalone/MySQL_update.php?world={world}&ts={timestamp}',
                         sendmessage: 'https://minecraft.domain.ch/new/standalone/MySQL_sendmessage.php',
                         login: 'https://minecraft.domain.ch/new/standalone/MySQL_login.php',
                         register: 'https://minecraft.domain.ch/new/standalone/MySQL_register.php',
                         tiles: 'https://minecraft.domain.ch/new/standalone/MySQL_tiles.php?tile=',
                         markers: 'https://minecraft.domain.ch/new/standalone/MySQL_markers.php?marker='
                     }
                 },
            // },

            // These messages are used throughout LiveAtlas and can be translated here
            // If a message you want to translate isn't here, it is likely controlled by dynmap itself
            // see https://github.com/webbukkit/dynmap/wiki/Configuration.txt
            messages: {
            	chatNoMessages: 'No chat messages yet...',
                chatTitle: 'Chat',
                chatLogin: 'Please login to send chat messages',
                chatSend: 'Send',
                chatPlaceholder: 'Type your chat message here...',
                chatErrorUnknown: 'Unexpected error while sending chat message',
                chatErrorDisabled: 'Chat is not enabled',
            	serversHeading: 'Servers',
                worldsSkeleton: 'No maps have been configured',
                playersSkeleton: 'No players are currently online',
                playersTitle: 'Click to center on player\nDouble-click to follow player',
                playersTitleHidden: 'This player is currently hidden from the map\nDouble-click to follow player when they become visible',
                playersTitleOtherWorld: 'This player is in another world.\nClick to center on player\nDouble-click to follow player',
                playersSearchPlaceholder: 'Search players...',
                playersSearchSkeleton: 'No matching players found',
                followingHeading: 'Following',
                followingUnfollow: 'Unfollow',
                followingTitleUnfollow: 'Stop following this player',
                followingHidden: 'Currently hidden',
                linkTitle: 'Copy link to current location',
                loadingTitle: 'Loading...',
                locationRegion: 'Region',
                locationChunk: 'Chunk',
                contextMenuCopyLink: 'Copy link to here',
                contextMenuCenterHere: 'Center here',
                toggleTitle: 'Click to toggle this section',
                mapTitle: 'Map - Use the arrow keys to pan the map',
                layersTitle: 'Layers',
                copyToClipboardSuccess: 'Copied to clipboard',
                copyToClipboardError: 'Unable to copy to clipboard',

                loginTitle: 'Login/Register',
                loginHeading: 'Existing User',
                loginUsernameLabel: 'Username',
                loginPasswordLabel: 'Password',
                loginSubmit: 'Login',
                loginErrorUnknown: 'Unexpected error while logging in',
                loginErrorDisabled: 'Logging in is disabled on this server',
                loginErrorIncorrect: 'Incorrect username or password',
                loginSuccess: 'Logged in successfully',

                registerHeading: 'New User',
                registerDescription: `Enter your username and password, along with your registration code.

                        You can get a registration code by running /dynmap webregister in-game.`,
                registerConfirmPasswordLabel: 'Confirm Password',
                registerCodeLabel: 'Registration Code',
                registerSubmit: 'Register',
                registerErrorUnknown: 'Unexpected error during registration',
                registerErrorDisabled: 'Registration is disabled on this server',
                registerErrorVerifyFailed: 'The entered passwords do not match',
                registerErrorIncorrect: 'Registration failed, please check the entered details are correct',

                logoutTitle: 'Logout',
                logoutErrorUnknown: 'Unexpected error while logging out',
                logoutSuccess: 'Logged out successfully',

                closeTitle: 'Close',
            },

            ui: {
            	// If true, player markers will always be displayed in front of other marker types
            	playersAboveMarkers: true,

                // Whether to enable the player list search box
                playersSearch: true,

                // Use more compact pre-2.0 player marker style
                compactPlayerMarkers: false,
            },

            // Config version. Do not modify.
            version: 1
        };
    </script>

    <style>
        /* Theme colours */
        :root {
            --background-base: #222222; /* Foreground UI elements */
            --background-dark: #121212; /* Body/Splash screen/Shadows */
            --background-light: #363636; /* Scrollbars/inputs */
            --background-error: #771616; /* Errors */
            --background-marker: var(--background-dark); /* Map markers */

            --background-disabled: #555555; /* Disabled controls */
            --background-hover: #363636; /* :hovered buttons/menu items */
            --background-active: #6d6d6d; /* Button :active */
            --background-selected: #BDBDBD; /* Selected buttons/menu items */

            --outline-focus: #eeeeee; /* :focus outline */

            --border-radius: 0.5rem;
            --border-color: #333333; /* Control borders */
            --border-error: #cc0e0e;
            --box-shadow: 2px 2px 0px #111111;

            --text-base: rgba(255, 255, 255, 0.7); /* Normal text */
            --text-emphasis: rgba(255, 255, 255, 0.87); /* Chat messages/:focus inputs */
            --text-subtle: rgba(255, 255, 255, 0.5); /* Skeletons/secondary text */
            --text-disabled: var(--text-subtle); /* Disabled controls */
            --text-marker: var(--text-base); /* Map markers */

            --text-hover: var(--text-base); /* Text in :hover buttons */
            --text-active: var(--text-base); /* Text in :active buttons */
            --text-selected: var(--background-base); /* Text in selected buttons */
            --text-shadow: 0.1rem 0.1rem #000000; /* Text in selected buttons */

            --text-night: #ddffff; /* Clock time at night */
            --text-day: #ffdd33; /* Clock time in day */
        }

        @keyframes fade {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }

        * {
            scrollbar-width: thin;
            scrollbar-color: var(--background-light) transparent;
        }

        *:hover, *:focus-within {
            scrollbar-color: var(--background-hover) transparent;
        }

        *::-webkit-scrollbar {
            width: 0.7rem;
        }

        *::-webkit-scrollbar-track {
            background: transparent;
        }

        *::-webkit-scrollbar-thumb {
            background-color: var(--background-light);
            border: 2px solid #000000;
            border-radius: 2rem;
            transition: background 1s ease-in;
            padding-right: 0.2rem;
        }

        *:hover::-webkit-scrollbar-thumb, *:focus-within::-webkit-scrollbar-thumb {
          background-color: var(--background-hover);
        }

        *::-webkit-scrollbar-button {
            display: none;
        }

        html, body {
            background-color: var(--background-dark);
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
	        overscroll-behavior: none;
        }

        html {
            font-size: 62.5%;
        }

        body {
            font-family: Raleway,
            system-ui,
            -apple-system,
            'Segoe UI',
            Roboto,
            Helvetica,
            Arial,
            sans-serif,
            'Apple Color Emoji',
            'Segoe UI Emoji';
            color: var(--text-base);
            text-shadow: var(--text-shadow);
            letter-spacing: 0.02rem;
        }

        noscript {
            color: var(--text-base);
            font-size: 1rem;
            font-family: sans-serif;
            text-align: center;
            line-height: 1.25;
        }

        #splash, noscript {
            position: fixed;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            transition: 0.3s opacity linear;
            z-index: 100;
            background-color: var(--background-dark);
            cursor: wait;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            font-size: 1.6rem;
            padding: 4rem;
        }

        #splash[hidden] {
            display: none;
        }

        #splash__spinner {
            margin-top: 4rem;
            animation: fade 0.5s linear 1s;
            animation-fill-mode: both;
        }

        #splash__error {
            margin-top: 2rem;
            transition: opacity 0.5s ease-in;
            display: flex;
            flex-direction: column;
            text-align: center;
            max-width: 60rem;
        }

        #splash__error-message {
            font-family: monospace;
            background-color: var(--background-error);
            padding: 1rem 1.5rem;
            border-radius: var(--border-radius);
            margin-bottom: 1rem;
        }

        #splash__error[aria-hidden=true] {
            opacity: 0;
        }

        #app {
            font-size: 1.6rem;
            height: 100%;
        }
    </style>
    <script type="module" crossorigin src="./live-atlas/assets/index.432fd330.js"></script>
    <link rel="modulepreload" href="./live-atlas/assets/vendor.3a2d484d.js">
    <link rel="stylesheet" href="./live-atlas/assets/index.c1ea5274.css">
  </head>
  <body>
    <div id="splash">
        <svg id="splash__logo" width="200" height="200" viewBox="0 0 268.83 266.53" aria-hidden="true" fill="rgba(255, 255, 255, 0.7)">
            <path d="M5.235.662C2.153.606 0 2.945 0 6.912v216.577c0 5.288 3.828 11.41 8.582 13.725l57.835 28.165c4.755 2.316 8.582-.078 8.582-5.367V43.434c0-5.288-3.827-11.41-8.582-13.727L8.582 1.544C7.394.965 6.262.681 5.235.662zm32.283 135.96c14.394 0 26.062 11.669 26.062 26.063 0 14.394-24.167 59.55-26.062 57.654-1.854 1.854-26.063-43.26-26.063-57.654 0-14.394 11.669-26.063 26.063-26.063zM202.388 1.013l57.833 28.165c4.755 2.315 8.583 8.437 8.583 13.726v216.58c0 5.29-3.828 7.683-8.583 5.367l-57.833-28.164c-4.755-2.316-8.583-8.438-8.583-13.727V6.38c0-5.289 3.828-7.682 8.583-5.367zM172.012.39c-1.051-.035-2.209.191-3.426.709l-68.342 29.053c-4.867 2.07-8.786 7.993-8.786 13.282V260.01c0 5.29 3.919 7.88 8.786 5.811l68.342-29.053c4.867-2.07 8.786-7.991 8.786-13.28V6.91c0-3.967-2.204-6.417-5.36-6.521zm-36.949 41.216c14.394 0 26.063 11.668 26.063 26.062 0 14.394-24.168 59.55-26.063 57.655C133.209 127.177 109 82.063 109 67.668c0-14.394 11.669-26.062 26.063-26.062z"/>
            <path d="M48.573 162.689a11.056 11.056 0 0 1-11.056 11.056 11.056 11.056 0 0 1-11.056-11.056 11.056 11.056 0 0 1 11.056-11.056 11.056 11.056 0 0 1 11.056 11.056zM146.12 67.669a11.056 11.056 0 0 1-11.057 11.056 11.056 11.056 0 0 1-11.056-11.056 11.056 11.056 0 0 1 11.056-11.056 11.056 11.056 0 0 1 11.056 11.056z"/>
        </svg>

        <svg id="splash__spinner" width="38" height="38" viewBox="0 0 38 38" stroke="#fff" aria-label="LiveAtlas is loading">
            <g transform="translate(1 1)" stroke-width="2" fill="none">
                <circle stroke-opacity=".5" cx="18" cy="18" r="18"/>
                <path d="M36 18c0-9.94-8.06-18-18-18">
                    <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"/>
                </path>
            </g>
        </svg>

        <div id="splash__error" aria-hidden="true">
            <span id="splash__error-message" role="alert"></span>
            <span id="splash__error-retry" aria-live="polite"></span>
        </div>
    </div>

    <noscript>
        <strong>LiveAtlas requires JavaScript to work.<br />Please enable it to continue.</strong>
    </noscript>

    <main id="app" aria-hidden="true"></main>
    
  </body>
</html>
`

If anyone could pinpoint me to my error, that would be great.

The two instances of Dynmap server in /old and /new are working as intended. The files requested are there.

I am running Ubuntu with NGINX. Dynmap is using mysql as storage. mysql, php, php-fpm etc. is installed. As I said, the dynmap servers itself work fine.

Thank you.

**Comment by JLyne** [comment]
At a glance it looks like you haven't uncommented the `servers` object at the top of `window.liveAtlasConfig`
![image](https://user-images.githubusercontent.com/4615316/147513175-50f9f1b2-8108-480a-be7e-77f225a6612b.png)

**Comment by redxon** [comment]
Unfortunately this wasn't it. Even after I uncommented this and the closing bracket, the error remains the same.

On 28 Dec 2021, at 00:21, James Lyne ***@***.***> wrote:

﻿

At a glance it looks like you haven't uncommented the servers object at the top of window.liveAtlasConfig
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F4615316%2F147513175-50f9f1b2-8108-480a-be7e-77f225a6612b.png&data=04%7C01%7C%7C73c1ab84b88a42c65a3f08d9c98f98b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762440843279210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TXi4mmfWfGD60lI8LoZtHMHIpNPB8wfgJP8tpmJrxzs%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJLyne%2FLiveAtlas%2Fissues%2F288%23issuecomment-1001796430&data=04%7C01%7C%7C73c1ab84b88a42c65a3f08d9c98f98b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762440843279210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Vb9%2FWmOgIhMix5NzU%2FP8SWa3QKu7nTt6bCDD4c5jnp0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPGDNKXGSLK7EVA2R66B3LUTDYHDANCNFSM5KNPF36A&data=04%7C01%7C%7C73c1ab84b88a42c65a3f08d9c98f98b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762440843279210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3ev85TuttYbOWQeVtYBl6otcAQpWqHm0VyXA5ZSwc%2Bc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C73c1ab84b88a42c65a3f08d9c98f98b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762440843279210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MXA3mUOMjOiW8p6Abz4oDUftClPWMqMLNmIyvkaah4s%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C73c1ab84b88a42c65a3f08d9c98f98b9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637762440843279210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SwLAZ5HBBCd%2FrTZhb0WhRAkbgvZ4EPdFK76ADyI5Opg%3D&reserved=0>.
