### ISSUE TITLE
Dynmap claims are being cut off

### ISSUE THREAD

**Issue by Sikatsu** [JLyne/LiveAtlas#29]
As the image displays, the top part of the dynmap claims are not visible sometimes. A hard reload seems to fix it.

![image](https://user-images.githubusercontent.com/5664135/121663276-8d5d0e80-caa6-11eb-8894-96f4467d1172.png)

**Comment by rymiel** [comment]
I can add to this with a similar issue of one side of the Worldborder being missing, for me it only ever seems to happen when **switching between the flat and surface**/isometric **views**. Switching to another world fixes it
![image](https://user-images.githubusercontent.com/53803019/121784805-ba044980-cbbe-11eb-8850-51256c21c554.png)
