### ISSUE TITLE
[Plexmap] Support for Continued Fork of Pl3xmap (Squaremap)

### ISSUE THREAD

**Issue by EuanM199** [JLyne/LiveAtlas#295]
Since Pl3xmap is not being discontinued past 1.17, could we please get Support for the continued fork of pl3xmap, called Square map, 
here is the link

[https://github.com/jpenilla/squaremap](https://github.com/jpenilla/squaremap)

**Comment by JLyne** [comment]
LiveAtlas currently supports both Squaremap and [NeumimTo's fork](https://github.com/NeumimTo/Pl3xMap) of Pl3xmap. I'll try to keep both of them supported as they are both currently actively used.

I'll update the readme etc to mention squaremap.
