### ISSUE TITLE
How do I make the layer box expand to the size of the text?

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#32]
![Screenshot 2021-06-22 at 11 08 39](https://user-images.githubusercontent.com/144046/122906659-4bf01d00-d34a-11eb-81ec-600c98dc65ce.png)

I just found out about this AMAZING project, thank you so much for keeping Dynmap and just improving the Web UI, its much needed.
I've been trialing it via https://api.piratemc.com/atlas/ (Super hacky with the Cores links there haha)

First thing I noticed is that the layers box is not flexible to the text inside (Player settlements). Could we get this fixed please.

Thank you.

**Comment by JLyne** [comment]
This should be fixed in 1.2.2

**Comment by TomLewis** [comment]
When updating do I just update `/live-atlas/assets` ? Ive started customizing my index & favicons etc so I cant just plop it on top!

**Comment by JLyne** [comment]
At a minimum you'll need to update `/live-atlas/assets` as well as the `<script>` and `<links>` pointing to them in index.html. It's is possible future updates will change index.html in other ways though, so it's probably best to diff the file when updating.
