### ISSUE TITLE
Feature Request: Replace functionality of Dynmap Addons

### ISSUE THREAD

**Issue by isaaclepes** [JLyne/LiveAtlas#324]
I like the look of this front-end, but I also really enjoy using some of the Dynmap addons:

These are the 3 that most interest me, but they also have addons for Towny, Citizens2, HeroChat, Factions, Residence, CommandBook, AdminCmd, and PreciousStones.
https://dev.bukkit.org/projects/dynmap-worldguard
https://dev.bukkit.org/projects/dynmap-griefprevention
https://dev.bukkit.org/projects/dynmap-essentials

I know many of these have not seen an update in a long time, but they still function.

**Comment by JLyne** [comment]
All the Dynmap addons which add extra markers to the map should work fine with LiveAtlas, as all it'll see are extra markers to display. I'm currently using Dynmap-WorldGuard and Plot2Dynmap without issue.

Addons which modify the frontend will likely not work, but I've not come across one of those so far. If any addons aren't working though, you can create an issue and I'll see what I can do.
