### ISSUE TITLE
Map types incorrect for many maps in one world (v3.0.0-beta.1)

### ISSUE THREAD

**Issue by stresli** [JLyne/LiveAtlas#345]
Hi,

we have a server with three worlds (multiverse):  world ( 4 maps), world_nether ( 2 maps) and world_the_end ( 2 maps). We wanted to display all in one section, so we added <append_to_world: 'world'> in the configuration dynmap for world_nether and world_the_end.  In the original dynmap this works as expected, but in LiveAtlas it doesn't display correctly.

<img width="148" alt="2022-02-02_19-05-12" src="https://user-images.githubusercontent.com/85819870/152228409-d8d3df8b-f578-4a30-b01b-759a6cb7ffaa.png">
<img width="203" alt="2022-02-02_19-05-52" src="https://user-images.githubusercontent.com/85819870/152228445-88cb5804-8aca-4aea-af32-f696688bdfba.png">

**Comment by JLyne** [comment]
Hopefully fixed in the [latest build](https://github.com/JLyne/LiveAtlas/actions/runs/1797316578). Quite a few changes needed for this so would appreciate some testing.
