### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by xEchoes** [JLyne/LiveAtlas#389]
Im getting this error, and idk why, all files are there when loading the map

LiveAtlas configuration is invalid:
Dynmap configuration object missing.
Check your standalone/config.js file exists and is being loaded correctly.

**Comment by JLyne** [comment]
With the limited information provided I cannot help much beyond repeating what the error is saying.

LiveAtlas was unable to find a dynmap configuration. The most likely cause for this is that your standalone/config.js file is missing. This is a file created by dynmap which contains the URLs to use for interacting with dynmap. Without it LiveAtlas cannot do anything as even determining which maps are available requires a URL contained in that file.

The solution depends on your configuration. If you are using the default internal webserver dynmap configuration, then perhaps ask the dynmap team for help as that file should exist.

If you are attempting to setup an external webserver, then ensure you have correctly followed [dynmap's instructions for this](https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics).
