### ISSUE TITLE
Infinity loading

### ISSUE THREAD

**Issue by rakzoser** [JLyne/LiveAtlas#404]
https://map.bromine.me/
Hi, just installed and have got infinity loading page
Maybe anyone got some ideas?

**Comment by Pawwandaa** [comment]
+1

**Comment by ModDownloader** [comment]
+1

**Comment by qqsob** [comment]
+1

**Comment by JLyne** [comment]
An endless loading screen indicates that LiveAtlas Javascript isn't loading correctly. Your browser console will provide more information as to why, but the most likely cause is that some files are missing entirely, or are trying to be fetched from the wrong URLs due to misconfiguration.
