### ISSUE TITLE
"disableMarkerUI: true" issue with sidebaropened set on pinned

### ISSUE THREAD

**Issue by Rysanlos** [JLyne/LiveAtlas#405]
Hello.

When we disable the markers button and list with `disableMarkerUI: true`
It's disabled, but with `sidebaropened: pinned` in the Dynmap configuration.txt
it's showing like this:
![image](https://user-images.githubusercontent.com/22010386/163567764-9ccd987b-c78e-4800-bb61-48980b267fa2.png)
The markers list should not be showing. (and we can't even dismiss it).
![image](https://user-images.githubusercontent.com/22010386/163568046-b1da7560-4906-4a74-88d7-906ce7790607.png)

Also, 
![image](https://user-images.githubusercontent.com/22010386/163567838-c742a865-193f-4047-a4e0-65b5dd7fb6f6.png)
this should be disabled if `disableMarkerUI: true`, or add a new option to disable it.

Thank you

**Comment by Rysanlos** [comment]
I fixed the first issue by deleting markers json files in `web/tiles/_markers_`
![image](https://user-images.githubusercontent.com/22010386/163568608-c0d2184a-129e-41fd-838b-b44af04e6213.png)

**Comment by JLyne** [comment]
Yeah that first part is a bug for sure, will work on that.

> Also,
> ![image](https://user-images.githubusercontent.com/22010386/163567838-c742a865-193f-4047-a4e0-65b5dd7fb6f6.png)
> this should be disabled if `disableMarkerUI: true`, or add a new option to disable it.

You can set `showlayercontrol: false` in dynmap's configuration.txt to hide the layers button

**Comment by Rysanlos** [comment]
After a server restart, the markers are back, so yes it is still an issue.

> You can set showlayercontrol: false in dynmap's configuration.txt to hide the layers button
Thank you, this is what I was looking for
