### ISSUE TITLE
"Theme" Option for Opacity for backgrond in UI elements.

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#41]
Something was bugging me and it just clocked what it is, when you open a UI item, it's fully opaque.
Dynmap actually has opacity with the player UI, so you can see what's behind it.

![Screenshot 2021-06-24 at 13 11 18](https://user-images.githubusercontent.com/144046/123260845-f48ab200-d4ed-11eb-9a01-947889e81922.png)

Can we please get a "theme" variable for how opaque we want the pop out UI background?

**Comment by JLyne** [comment]
With the latest commit this is now possible by changing the `--background-base` variable to a semi-transparent value (such as dynmap's `rgba(0, 0, 0, 0.6)`.

You may also want to set `--text-hover` to a different value (such as `#222222`) to improve contrast on hovered buttons if you choose to do this.
