### ISSUE TITLE
Multi server config

### ISSUE THREAD

**Issue by Rectos28** [JLyne/LiveAtlas#418]
I am having issues regarding configuring for the multi server. The wiki page is so broad and don't help that much. As what you stated on the 3 options in setting the multi host in this [page](https://github.com/JLyne/LiveAtlas/issues/393). **for the third option which is:** 
`Turn off the internal webservers, configure your external webserver to point to the web/standalone folder on each backend server.`

I am trying to do that but with no luck .

Here is my setup (btw am using docker container to point the folder to each one):
**1. The database container for each server:** creativer-db , survival-db
**2. The server containers:** creativer-server , survival-server
**3. The webserver container (containg LiveAtlas):** webserver 
**4. The reverse proxy container ([npm](https://nginxproxymanager.com/)):** proxy

I have connected all the container togather and I can confirm each server dynmap internal webserver was working like charm whith no issues before chosing to connect them to one webserver. After going to this setup I got this error:

`Failed to load server configuration for 'survival'
Error: Network request failed (Unknown)`

LiveAtlas `index.html ` setup:
```
servers: {
               creative: {
                 label: 'Creative',
                 dynmap: {
                     configuration: './standalone/creative/MySQL_configuration.php',
                     update: './standalone/creative/MySQL_update.php?world={world}&ts={timestamp}',
                     sendmessage: './standalone/creative/MySQL_sendmessage.php',
                     login: './standalone/creative/MySQL_login.php',
                     register: './standalone/creative/MySQL_register.php',
                     tiles: './standalone/creative/MySQL_tiles.php?tile=',
                     markers: './standalone/creative/MySQL_markers.php?marker='
                 }
               },
               survival: {
                 label: 'Survival',
                 dynmap: {
                     configuration: './standalone/survival/MySQL_configuration.php',
                     update: './standalone/survival/MySQL_update.php?world={world}&ts={timestamp}',
                     sendmessage: './standalone/survival/MySQL_sendmessage.php',
                     login: './standalone/survival/MySQL_login.php',
                     register: './standalone/survival/MySQL_register.php',
                     tiles: './standalone/survival/MySQL_tiles.php?tile=',
                     markers: './standalone/survival/MySQL_markers.php?marker='
			     }
               },
```

where the `./standalone/survival` is maped to `/survival-server/plugins/dynmap/web/standalone` the same for creative server.
Hope you can help.

**Comment by asvany** [comment]
I have a very similar situation:
"Failed to load server configuration for 'dynmap'
Error: Network request failed"

config in index.html:
```

     servers: {
               dynmap: {
                 label: 'FTB Endevaour',
                 dynmap: {
                     configuration: 'https://dynmap.mongoose.space/standalone/MySQL_configuration.php',
                     update: 'https://dynmap.mongoose.space/standalone/MySQL_update.php?world={world}&ts={timestamp}',
                     sendmessage: 'https://dynmap.mongoose.space/standalone/MySQL_sendmessage.php',
                     login: 'https://dynmap.mongoose.space/standalone/MySQL_login.php',
                     register: 'https://dynmap.mongoose.space/standalone/MySQL_register.php',
                     tiles: 'https://dynmap.mongoose.space/standalone/MySQL_tiles.php?tile=',
                     markers: 'https://dynmap.mongoose.space/standalone/MySQL_markers.php?marker='
             }
               }
             },

```

the browser console:


The URLs work well in the localnet; certificates are valid.
The dynmap site also works without any issues.

**Comment by asvany** [comment]
fixed for me, via valid cors config in Nginx:

```
    add_header Access-Control-Allow-Origin https://maps.mongoose.space;
    add_header Access-Control-Allow-Credentials true;

```
