### ISSUE TITLE
Release 1.2.3, missing files

### ISSUE THREAD

**Issue by AdrianHDev** [JLyne/LiveAtlas#42]
[Release 1.2.3](https://github.com/JLyne/LiveAtlas/releases/tag/v1.2.3)'s zip is incomplete and does not have all files necessary to be used.

**Comment by JLyne** [comment]
I have received no other reports of missing files, and the download appears to function correctly for me.

Please confirm you have already setup vanilla dynmap in the location you are attempting to use LiveAtlas. LiveAtlas requires either the `standalone/config.js` file from a functioning dynmap install to exist, or for servers to be configured directly in index.html [as described here](https://github.com/JLyne/LiveAtlas/wiki/Configuring-Multiple-Servers).

Feel free to reopen this issue if the problem persists for you, ideally with any error messages you see in your browser console.
