### ISSUE TITLE
Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#425]
Self hosted Dynmap https://map.piratemc.com/
Self hosted LiveAtlas https://atlas.piratemc.com/

I setup my nginx to allow cors 
https://enable-cors.org/server_nginx.html

This says its a client side issue https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

I even tried with a cors proxy.

And I even tried on a separate web server, that's actually on the same machine as the dynmap itself!
https://api.piratemc.com/atlas/

Can not get past Cors, even when I have set nginx to allow it.

**Comment by TomLewis** [comment]
I figured it out myself.

In Nginx you need to specify exactly what the URL is, you cant use * for some reason any more for  ccess-Control-Allow-Origin AND you need to set Access-Control-Allow-Credentials.

```
        location / {
                add_header Access-Control-Allow-Origin https://atlas.piratemc.com;
                add_header Access-Control-Allow-Credentials true;
        }
```

**Comment by TomLewis** [comment]
Right, I moved my main live map to Atlas, but im getting Cors errors with 404, loads of them.
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://smap.piratemc.com/tiles/PirateCraft_1/t/16_-4/zzzzzz_512_-128.png. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.```

Why is it trying to load something that does not exist?

**Comment by JLyne** [comment]
This is expected behaviour as the only way LiveAtlas can determine whether a map tile for a given area exists is to request it. Dynmap does not provide sufficient information to the frontend to avoid this, likely because it isn't worth the overhead when simply displaying nothing if the tile doesn't exist is sufficient.

**Comment by JLyne** [comment]
Regarding the cors errors though, you can add `always` to the end of your `add_header` lines to fix that. By default nginx won't add the headers for 404 responses.

**Comment by TomLewis** [comment]
Setting to always seems to have calmed down the console a bit!
