### ISSUE TITLE
Add .htaccess file with download.

### ISSUE THREAD

**Issue by TomLewis** [JLyne/LiveAtlas#426]
Does not have an Apache config for /servername for multi server.

After lots of messing around with no exmaple in the wiki I found this to work;
```
RewriteEngine On 
RewriteCond %{REQUEST_FILENAME} !-d

FallbackResource /index.html
```

Alternativly could just be added to: 
https://github.com/JLyne/LiveAtlas/wiki/Configuring-Multiple-Servers

The reason ive not edited it into the wiki myself, is im not sure im doing this the correct way? I may not even need the RewriteCond.

**Comment by JLyne** [comment]
Added to the wiki
