### ISSUE TITLE
Version 1.3.0 and 1.3.1 refuse to load after untouched setup

### ISSUE THREAD

**Issue by CloudeLecaw** [JLyne/LiveAtlas#51]
Basic steps
we did in
1.2.3
- Download the jar
- Copy files to dynmap/web
- done
![22-07-_2021_23-27-47](https://user-images.githubusercontent.com/12080017/126714856-57e6fc13-12ce-4c79-b937-021719b54a47.png)

in 1.3.0 we tried this
![Snag_6d60dda](https://user-images.githubusercontent.com/12080017/126714879-89a8e5d0-3b5a-4728-975c-51458a8c31c6.png)
![Snag_6d624be](https://user-images.githubusercontent.com/12080017/126714885-64d4084f-5e64-40db-8ce3-d51faeacbf44.png)

and in 1.3.1
![Snag_6d64a76](https://user-images.githubusercontent.com/12080017/126714900-0e433f80-47ec-44af-933b-64994e17937b.png)

So what might went wrong now, that we cant use the easy setup anymore?
This is one of the cool things of your expansion that it is able to install so easy
now with 1.3.0 it seems to lost this abillity

So for us we went back to 1.2.3 for now..

I hope this can be fixed soon

Note: 
We just have one server... so we never needed to set up anything until today..

**Comment by JLyne** [comment]
Will be fixed shortly in 1.3.2, I just left some test server configurations in the release index.html unintentionally
