### ISSUE TITLE
Required LiveAtlas files are missing or failed to load. Please reinstall LiveAtlas.

### ISSUE THREAD

**Issue by StonFlip** [JLyne/LiveAtlas#519]
There was a problem with an error from the header. I tried to reinstall LiveAtlas, without LiveAtlas the map works.

Map link: https://gefest.cbtpolit.xyz/

**Comment by JLyne** [comment]
The URLs in your index.html appear to have been modified and are not pointing to the correct locations. Specifically they have `/var/www/gefest.cbtpolit.xyz/` prepended, which appears to be a mistake as all of those URLs return 404s. Removing the modifications allows LiveAtlas to work correctly.
