### ISSUE TITLE
Latest code in master is broken after removing Control from Leaflet

### ISSUE THREAD

**Issue by jokrefta** [JLyne/LiveAtlas#585]
I cloned LiveAtlas and tried to build and run it, but the current version of the code appears to be broken. 

I see the following error in the Firefox console:
```
Uncaught TypeError: class heritage (intermediate value).Layers is not an object or null
  <anonymous> http://localhost:8080/src/leaflet/control/LiveAtlasLayerControl.ts:11
```

See the relevant line: https://github.com/JLyne/LiveAtlas/blob/9ab3becd5407126e5ee6f6e11bdababb8ab34f72/src/leaflet/control/LiveAtlasLayerControl.ts#L37

I think this was broken by https://github.com/JLyne/Leaflet/commit/4aa9e62e01dede9696cf43135a427895ea31565f which removed Control.

**Comment by JLyne** [comment]
This should be resolved. Thanks for the report.
