### ISSUE TITLE
Support for showing marker labels without hovering

### ISSUE THREAD

**Issue by SpaceYoshi** [JLyne/LiveAtlas#6]
Hi there,
In the Dynmap config there is an option to make the marker labels show by default (without hovering over them).
The setting is 'showlabel: true' I believe. I would like to see this feature. Thanks for making this add-on.

**Comment by JLyne** [comment]
I was sure this was already supported, but it seems I am not checking the global config value for it, only the per-markerset ones. Simple enough fix.
