### ISSUE TITLE
Squaremap-signs allows for injecting HTML

### ISSUE THREAD

**Issue by CodexNotFound** [JLyne/LiveAtlas#627]
Using the following sign:
![image](https://github.com/JLyne/LiveAtlas/assets/105505041/920e67aa-5b76-41cf-99a7-afcd2c8790f0)

I see the following result on the map:
![image](https://github.com/JLyne/LiveAtlas/assets/105505041/9750dfbb-bbab-4f25-8b3e-6e1a039e5d30)

This would also allow throwing an Error in the browser.

**Comment by JLyne** [comment]
This is an issue that needs fixing in squaremap-signs itself, as it is adding unsanitised user input into the marker tooltip and will be causing the same issue in the stock frontend.

Squaremap markers are allowed to include html in their tooltips and the official addons make frequent use of this, so it cannot be stripped out without breaking compatibility.
