### ISSUE TITLE
LiveAtlas not showing players

### ISSUE THREAD

**Issue by RealFX-Code** [JLyne/LiveAtlas#637]
I can't see players on my server for some reason through LiveAtlas. Intercepting some of the requests, it does indeed receive player data from dynmap, but doesn't display them.
![image](https://github.com/JLyne/LiveAtlas/assets/25106569/c40d54f4-8832-4431-aadf-78e1abde4541)

I haven't changed any settings at all, and have looked for settings that might hide players, yet I've found nothing

Thanks in advance.

**Comment by JLyne** [comment]
At a glance you appear to have a typo in your dynmap configuration.txt. The `playermarkers` component is instead misspelled `playermarkerl`. This stops LiveAtlas from adding the player marker layer, thus no markers appear.

Renaming `playermarkerl` to `playermarkers` should hopefully solve your problem.

**Comment by RealFX-Code** [comment]
> At a glance you appear to have a typo in your dynmap configuration.txt. The `playermarkers` component is instead misspelled `playermarkerl` (unless this is a new dynmap thing I'm not aware of). This stops LiveAtlas from adding the player marker layer, thus no markers appear.
> 
> Renaming `playermarkerl` to `playermarkers` should hopefully solve your problem.

Thank you so much! I can't believe it was that simple, It now works just as it should.
