### ISSUE TITLE
[BUG] isn't work on squremap

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [JLyne/LiveAtlas#642]
your pack can work good on dynmap and pl3xmap, but squremap cannot used it, when server restarting the squrmap always del the LiveAtlas html and replace squremap's html
and thanks for your help :>

**Comment by justADeni** [comment]
installation instructions for squaremap:

> Open Squaremap/Pl3xmap's config.yml and set auto-update to false.

have you done that? specifically it's in `plugins/squaremap/config.yml` under `settings.web-directory.auto-update`

**Comment by xiaoyueyoqwq** [comment]
> installation instructions for squaremap:
> 
> > Open Squaremap/Pl3xmap's config.yml and set auto-update to false.
> 
> have you done that? specifically it's in `plugins/squaremap/config.yml` under `settings.web-directory.auto-update`

Hi
Thanks for your reply and I think I already solved this problem, thanks
