### ISSUE TITLE
Failed to retrieve face of...

### ISSUE THREAD

**Issue by Leonardo-Fiori** [JLyne/LiveAtlas#73]
Player faces aren't loading, look at the dev. console 😄 
`Failed to load resource: the server responded with a status of 500 ()`

https://www.peacefulvanilla.club/maps

Do you have any idea on what is causing this? Internal dynmap webserver with nginx webserver on top. Under cloudflare.

dynmap version 3.1-457
liveatlas 2.0.0-beta.1

**Comment by JLyne** [comment]
Looks like the same issue as #2 
It's since been fixed but isn't included in a release yet, You can wait for the next release or try [this version](https://github.com/JLyne/LiveAtlas/actions/runs/1090922668) in the meantime
