### ISSUE TITLE
Multi Server

### ISSUE THREAD

**Issue by CraftJunkies** [JLyne/LiveAtlas#83]
Is multiserver only possible with dynmap over mysql? or is it with json possible to

**Comment by JLyne** [comment]
JSON should be possible too yes. The only requirements are 1. The URLs are configured correctly on LiveAtlas' end (You'd typically copy them from the standalone/config.js on each server), and 2. Those URLs are accessible from a browser.

See [the wiki page](https://github.com/JLyne/LiveAtlas/wiki/Configuring-Multiple-Servers) for more information on the required steps.
