### ISSUE TITLE
Add Apache Rewrite Rules to Wiki

### ISSUE THREAD

**Issue by CraftJunkies** [JLyne/LiveAtlas#84]
Can someone please add the rewrite rules for apache to the wiki? Trying since ~2h but dont get it to work with multiserver

**Comment by turiaso** [comment]
Hi, 
I set this in minecraft.conf file

RewriteEngine On
  RewriteRule "^/minecraft/lobby/(.*)$"    "http://192.168.1.X:8123/$1" [P]
  RewriteRule "^/minecraft/base/(.*)$"     "http://192.168.1.Y:8123/$1" [P]

all redirects show the associated DynMap but Atlas' index.html no load /minecraft/lobby//standalone/MySQL_configuration.php.

Could you help me?

Regards!

**Comment by JLyne** [comment]
An apache example is now in the wiki
